name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.6
  - pip3.9
  - pip3.9:
    - matplotlib==3.5.2
    - dill==0.3.4
    - pandas==1.3.5
    - seaborn==0.11.2
    - sklearn==1.0.1